# Generated by Django 2.2.7 on 2020-10-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteForum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='enquete',
            name='tipo',
            field=models.ManyToManyField(blank=True, to='siteForum.tipo'),
        ),
    ]
