# Generated by Django 2.2.7 on 2020-10-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteForum', '0002_auto_20201019_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquete',
            name='tipo',
        ),
        migrations.AddField(
            model_name='enquete',
            name='tipo',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Html', 'Html'), ('CSS', 'CSS'), ('Linux', 'Linux'), ('Bootstrap', 'Bootstrap'), ('FontAwesome', 'FontAwesome')], default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='tipo',
        ),
    ]
