# Generated by Django 2.2.7 on 2020-10-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteForum', '0003_auto_20201019_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Html', 'Html'), ('CSS', 'CSS'), ('Linux', 'Linux'), ('Bootstrap', 'Bootstrap'), ('FontAwesome', 'FontAwesome')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='enquete',
            name='tipo',
        ),
        migrations.AddField(
            model_name='enquete',
            name='tipo',
            field=models.ManyToManyField(blank=True, to='siteForum.tipo'),
        ),
    ]
