# Generated by Django 2.2.7 on 2020-10-20 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteForum', '0005_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='dono',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
