# Generated by Django 2.2.7 on 2020-10-20 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteForum', '0007_auto_20201020_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='dono',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
