# Generated by Django 2.2.7 on 2020-10-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteForum', '0009_resposta_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resp',
            field=models.TextField(verbose_name='Resposta'),
        ),
        migrations.CreateModel(
            name='avaliacaoResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aval', models.IntegerField()),
                ('resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteForum.resposta')),
            ],
        ),
    ]
