# Generated by Django 2.2.7 on 2020-10-21 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteForum', '0010_auto_20201021_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoresp',
            name='dono',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
