# Generated by Django 2.2.7 on 2020-10-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteForum', '0011_avaliacaoresp_dono'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('mostrarNome', models.BooleanField()),
                ('mostrarEmail', models.BooleanField()),
                ('mostrarFoto', models.BooleanField()),
                ('mostrarNascimento', models.BooleanField()),
            ],
        ),
    ]
