# Generated by Django 2.2.7 on 2020-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteForum', '0013_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
